#lang racket

(define (find_cubeV)
  (display "Вычисление объема куба.")
  (newline)
  (display "Введите длину ребра (см) и нажмите клавишу <Enter> =")
  (define a (read))
  (define cube_V (* a a a))
  (display "Объем куба: ")
  (display cube_V)
  (display " куб.см."))

(define (find_cilV)
  (display "Вычисление объема цилиндра.")
  (newline)
  (display "Введите исходные данные:")
  (newline)
  (display "радиус основания (см) = ")
  (define r (read))
  (display "высота цилиндра (см) = ")
  (define h (read))
  (define pi 3.14)
  (define cil_V (* pi (* r r)))
  (display "Объем цилиндра ")
  (display cil_V)
  (display " см. куб."))

(define (pokupki)
  (display "Вычисление стоимости покупки.")
  (newline)
  (display "Введите исходные данные:")
  (newline)
  (display "Цена тетради (руб.) = ")
  (define ct (read))
  (display "Количество тетрадей = ")
  (define kt (read))
  (display "Цена карандаша (руб.) = ")
  (define ck (read))
  (display "Количество карандашей = ")
  (define kk (read))
  (display "Стоимость покупки: ")
  (define buy_summ (+ (* ct kt)(* ck kk)))
  (display buy_summ)
  (display " руб."))

;(find_cubeV)
;(find_cilV)
(pokupki)